"""Declarative educational rules. No commands or payloads are executed."""

RULES = [
    {
        "id": "RULE-001",
        "event_type": "failed_login",
        "name": "Repeated failed logins",
        "title": "Possible Brute Force Authentication Attempt",
        "severity": "HIGH",
        "description": "Repeated failures for one source IP and user.",
        "logic": "At least the configured threshold in the rolling time window; suppress repeat alerts for that pair for one window.",
        "recommendation": "Review authentication history and verify with the account owner; simulate access restriction if warranted.",
        "false_positive": "Mistyped passwords, a stale application password, or a shared test account.",
        "investigation": "Compare user, source, timestamps, and any later successful login.",
        "mapping": "Credential Access concept; T1110 Brute Force",
    },
    {
        "id": "RULE-002",
        "event_type": "powershell",
        "name": "Suspicious PowerShell",
        "title": "Suspicious PowerShell Activity",
        "severity": "HIGH",
        "description": "A simulator event flagged as suspicious script activity.",
        "logic": "event_type equals powershell.",
        "recommendation": "Review synthetic script context and simulate endpoint isolation.",
        "false_positive": "Approved administration or automation.",
        "investigation": "Validate the operator and change ticket; inspect synthetic event details.",
        "mapping": "Execution concept; T1059.001 PowerShell",
    },
    {
        "id": "RULE-003",
        "event_type": "privilege_change",
        "name": "Privilege change",
        "title": "Unexpected Privilege Change",
        "severity": "HIGH",
        "description": "A synthetic role assignment changed.",
        "logic": "event_type equals privilege_change.",
        "recommendation": "Verify authorization and record a simulated role rollback.",
        "false_positive": "Approved access provisioning.",
        "investigation": "Check the fictional approver, role, and business need.",
        "mapping": "Privilege Escalation concept; no technique attribution",
    },
    {
        "id": "RULE-004",
        "event_type": "malware",
        "name": "Malware indicator",
        "title": "Malware Detection Event",
        "severity": "CRITICAL",
        "description": "A fictitious endpoint protection verdict; no malware exists.",
        "logic": "event_type equals malware.",
        "recommendation": "Simulate containment and record clean recovery validation.",
        "false_positive": "A benign test artifact incorrectly classified by a sensor.",
        "investigation": "Validate the synthetic verdict and determine the affected host scope.",
        "mapping": "No unique ATT&CK technique inferred from a malware label",
    },
    {
        "id": "RULE-005",
        "event_type": "file_modification",
        "name": "Important file change",
        "title": "Critical File Modification",
        "severity": "MEDIUM",
        "description": "A simulated important configuration file changed.",
        "logic": "event_type equals file_modification.",
        "recommendation": "Compare the approved baseline and simulate restoring it.",
        "false_positive": "Approved deployment or configuration update.",
        "investigation": "Review the fictional change ticket and baseline differences.",
        "mapping": "No unique tactic or technique without change context",
    },
    {
        "id": "RULE-006",
        "event_type": "network_anomaly",
        "name": "Network anomaly",
        "title": "Suspicious Network Activity",
        "severity": "MEDIUM",
        "description": "A synthetic unusual connection pattern.",
        "logic": "event_type equals network_anomaly.",
        "recommendation": "Investigate destination context and simulate an egress restriction.",
        "false_positive": "Legitimate scheduled synchronization.",
        "investigation": "Inspect timing, frequency, destination and business purpose.",
        "mapping": "Command and Control concept only; no proof of C2",
    },
    {
        "id": "RULE-007",
        "event_type": "account_creation",
        "name": "Account creation",
        "title": "New Account Created",
        "severity": "MEDIUM",
        "description": "A new fictional account needs validation.",
        "logic": "event_type equals account_creation.",
        "recommendation": "Verify provisioning approval; record simulated suspension if unapproved.",
        "false_positive": "Authorized onboarding.",
        "investigation": "Compare account creation to the approved request.",
        "mapping": "Persistence concept only; legitimate creation is common",
    },
    {
        "id": "RULE-008",
        "event_type": "normal",
        "name": "Normal activity",
        "title": "Normal activity",
        "severity": "LOW",
        "description": "Routine simulated activity and successful logins are stored without alerts.",
        "logic": "normal and successful_login produce no alert.",
        "recommendation": "Retain for context; no response required.",
        "false_positive": "Not applicable: no alert generated.",
        "investigation": "Use as context alongside suspicious events.",
        "mapping": "None",
    },
]
BY_EVENT = {r["event_type"]: r for r in RULES}
BY_ID = {r["id"]: r for r in RULES}
